package com.msr.entity;

import java.util.Date;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;
public class Clazz {
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.clazz_id
     *
     * @mbggenerated Mon Jul 08 10:48:09 JST 2019
     */
    private Integer clazzId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.clazz_name
     *
     * @mbggenerated Mon Jul 08 10:48:09 JST 2019
     */
    private String clazzName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.clazz_address
     *
     * @mbggenerated Mon Jul 08 10:48:09 JST 2019
     */
    private String clazzAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.clazz_startTime
     *
     * @mbggenerated Mon Jul 08 10:48:09 JST 2019
     */
    @DateTimeFormat(pattern ="yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+9")
    private Date clazzStarttime;
    

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.clazz_endTime
     *
     * @mbggenerated Mon Jul 08 10:48:09 JST 2019
     */
    @DateTimeFormat(pattern ="yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+9")
    private Date clazzEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.clazz_status
     *
     * @mbggenerated Mon Jul 08 10:48:09 JST 2019
     */
    private Integer clazzStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.clazz_note
     *
     * @mbggenerated Mon Jul 08 10:48:09 JST 2019
     */
    private String clazzNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.teacher_id
     *
     * @mbggenerated Mon Jul 08 10:48:09 JST 2019
     */
    private Integer teacherId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.clazz_id
     *
     * @return the value of clazz.clazz_id
     *
     * @mbggenerated Mon Jul 08 10:48:09 JST 2019
     */
    public Integer getClazzId() {
        return clazzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.clazz_id
     *
     * @param clazzId the value for clazz.clazz_id
     *
     * @mbggenerated Mon Jul 08 10:48:09 JST 2019
     */
    public void setClazzId(Integer clazzId) {
        this.clazzId = clazzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.clazz_name
     *
     * @return the value of clazz.clazz_name
     *
     * @mbggenerated Mon Jul 08 10:48:09 JST 2019
     */
    public String getClazzName() {
        return clazzName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.clazz_name
     *
     * @param clazzName the value for clazz.clazz_name
     *
     * @mbggenerated Mon Jul 08 10:48:09 JST 2019
     */
    public void setClazzName(String clazzName) {
        this.clazzName = clazzName == null ? null : clazzName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.clazz_address
     *
     * @return the value of clazz.clazz_address
     *
     * @mbggenerated Mon Jul 08 10:48:09 JST 2019
     */
    public String getClazzAddress() {
        return clazzAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.clazz_address
     *
     * @param clazzAddress the value for clazz.clazz_address
     *
     * @mbggenerated Mon Jul 08 10:48:09 JST 2019
     */
    public void setClazzAddress(String clazzAddress) {
        this.clazzAddress = clazzAddress == null ? null : clazzAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.clazz_startTime
     *
     * @return the value of clazz.clazz_startTime
     *
     * @mbggenerated Mon Jul 08 10:48:09 JST 2019
     */
    public Date getClazzStarttime() {
        return clazzStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.clazz_startTime
     *
     * @param clazzStarttime the value for clazz.clazz_startTime
     *
     * @mbggenerated Mon Jul 08 10:48:09 JST 2019
     */
    public void setClazzStarttime(Date clazzStarttime) {
        this.clazzStarttime = clazzStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.clazz_endTime
     *
     * @return the value of clazz.clazz_endTime
     *
     * @mbggenerated Mon Jul 08 10:48:09 JST 2019
     */
    public Date getClazzEndtime() {
        return clazzEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.clazz_endTime
     *
     * @param clazzEndtime the value for clazz.clazz_endTime
     *
     * @mbggenerated Mon Jul 08 10:48:09 JST 2019
     */
    public void setClazzEndtime(Date clazzEndtime) {
        this.clazzEndtime = clazzEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.clazz_status
     *
     * @return the value of clazz.clazz_status
     *
     * @mbggenerated Mon Jul 08 10:48:09 JST 2019
     */
    public Integer getClazzStatus() {
        return clazzStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.clazz_status
     *
     * @param clazzStatus the value for clazz.clazz_status
     *
     * @mbggenerated Mon Jul 08 10:48:09 JST 2019
     */
    public void setClazzStatus(Integer clazzStatus) {
        this.clazzStatus = clazzStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.clazz_note
     *
     * @return the value of clazz.clazz_note
     *
     * @mbggenerated Mon Jul 08 10:48:09 JST 2019
     */
    public String getClazzNote() {
        return clazzNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.clazz_note
     *
     * @param clazzNote the value for clazz.clazz_note
     *
     * @mbggenerated Mon Jul 08 10:48:09 JST 2019
     */
    public void setClazzNote(String clazzNote) {
        this.clazzNote = clazzNote == null ? null : clazzNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.teacher_id
     *
     * @return the value of clazz.teacher_id
     *
     * @mbggenerated Mon Jul 08 10:48:09 JST 2019
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.teacher_id
     *
     * @param teacherId the value for clazz.teacher_id
     *
     * @mbggenerated Mon Jul 08 10:48:09 JST 2019
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }
}