package com.msr.entity;

public class Company {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_id
     *
     * @mbggenerated Fri Jul 05 17:55:48 JST 2019
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_name
     *
     * @mbggenerated Fri Jul 05 17:55:48 JST 2019
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_address
     *
     * @mbggenerated Fri Jul 05 17:55:48 JST 2019
     */
    private String companyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_contact
     *
     * @mbggenerated Fri Jul 05 17:55:48 JST 2019
     */
    private String companyContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_tel
     *
     * @mbggenerated Fri Jul 05 17:55:48 JST 2019
     */
    private String companyTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_status
     *
     * @mbggenerated Fri Jul 05 17:55:48 JST 2019
     */
    private Integer companyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_note
     *
     * @mbggenerated Fri Jul 05 17:55:48 JST 2019
     */
    private String companyNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_photo
     *
     * @mbggenerated Fri Jul 05 17:55:48 JST 2019
     */
    private byte[] companyPhoto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_id
     *
     * @return the value of company.company_id
     *
     * @mbggenerated Fri Jul 05 17:55:48 JST 2019
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_id
     *
     * @param companyId the value for company.company_id
     *
     * @mbggenerated Fri Jul 05 17:55:48 JST 2019
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_name
     *
     * @return the value of company.company_name
     *
     * @mbggenerated Fri Jul 05 17:55:48 JST 2019
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_name
     *
     * @param companyName the value for company.company_name
     *
     * @mbggenerated Fri Jul 05 17:55:48 JST 2019
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_address
     *
     * @return the value of company.company_address
     *
     * @mbggenerated Fri Jul 05 17:55:48 JST 2019
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_address
     *
     * @param companyAddress the value for company.company_address
     *
     * @mbggenerated Fri Jul 05 17:55:48 JST 2019
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress == null ? null : companyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_contact
     *
     * @return the value of company.company_contact
     *
     * @mbggenerated Fri Jul 05 17:55:48 JST 2019
     */
    public String getCompanyContact() {
        return companyContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_contact
     *
     * @param companyContact the value for company.company_contact
     *
     * @mbggenerated Fri Jul 05 17:55:48 JST 2019
     */
    public void setCompanyContact(String companyContact) {
        this.companyContact = companyContact == null ? null : companyContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_tel
     *
     * @return the value of company.company_tel
     *
     * @mbggenerated Fri Jul 05 17:55:48 JST 2019
     */
    public String getCompanyTel() {
        return companyTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_tel
     *
     * @param companyTel the value for company.company_tel
     *
     * @mbggenerated Fri Jul 05 17:55:48 JST 2019
     */
    public void setCompanyTel(String companyTel) {
        this.companyTel = companyTel == null ? null : companyTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_status
     *
     * @return the value of company.company_status
     *
     * @mbggenerated Fri Jul 05 17:55:48 JST 2019
     */
    public Integer getCompanyStatus() {
        return companyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_status
     *
     * @param companyStatus the value for company.company_status
     *
     * @mbggenerated Fri Jul 05 17:55:48 JST 2019
     */
    public void setCompanyStatus(Integer companyStatus) {
        this.companyStatus = companyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_note
     *
     * @return the value of company.company_note
     *
     * @mbggenerated Fri Jul 05 17:55:48 JST 2019
     */
    public String getCompanyNote() {
        return companyNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_note
     *
     * @param companyNote the value for company.company_note
     *
     * @mbggenerated Fri Jul 05 17:55:48 JST 2019
     */
    public void setCompanyNote(String companyNote) {
        this.companyNote = companyNote == null ? null : companyNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_photo
     *
     * @return the value of company.company_photo
     *
     * @mbggenerated Fri Jul 05 17:55:48 JST 2019
     */
    public byte[] getCompanyPhoto() {
        return companyPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_photo
     *
     * @param companyPhoto the value for company.company_photo
     *
     * @mbggenerated Fri Jul 05 17:55:48 JST 2019
     */
    public void setCompanyPhoto(byte[] companyPhoto) {
        this.companyPhoto = companyPhoto;
    }
}