package com.msr.entity;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_id
     *
     * @mbggenerated Mon Jul 22 12:17:20 JST 2019
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_name
     *
     * @mbggenerated Mon Jul 22 12:17:20 JST 2019
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_level
     *
     * @mbggenerated Mon Jul 22 12:17:20 JST 2019
     */
    private Integer courseLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_date
     *
     * @mbggenerated Mon Jul 22 12:17:20 JST 2019
     */
    private Integer courseDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_id
     *
     * @return the value of course.course_id
     *
     * @mbggenerated Mon Jul 22 12:17:20 JST 2019
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_id
     *
     * @param courseId the value for course.course_id
     *
     * @mbggenerated Mon Jul 22 12:17:20 JST 2019
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_name
     *
     * @return the value of course.course_name
     *
     * @mbggenerated Mon Jul 22 12:17:20 JST 2019
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_name
     *
     * @param courseName the value for course.course_name
     *
     * @mbggenerated Mon Jul 22 12:17:20 JST 2019
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_level
     *
     * @return the value of course.course_level
     *
     * @mbggenerated Mon Jul 22 12:17:20 JST 2019
     */
    public Integer getCourseLevel() {
        return courseLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_level
     *
     * @param courseLevel the value for course.course_level
     *
     * @mbggenerated Mon Jul 22 12:17:20 JST 2019
     */
    public void setCourseLevel(Integer courseLevel) {
        this.courseLevel = courseLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_date
     *
     * @return the value of course.course_date
     *
     * @mbggenerated Mon Jul 22 12:17:20 JST 2019
     */
    public Integer getCourseDate() {
        return courseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_date
     *
     * @param courseDate the value for course.course_date
     *
     * @mbggenerated Mon Jul 22 12:17:20 JST 2019
     */
    public void setCourseDate(Integer courseDate) {
        this.courseDate = courseDate;
    }
    //多表添加字段
    private String levelName;
    private String titleName;
    private String courseContent;
    private String couName;

	public String getLevelName() {
		return levelName;
	}

	public void setLevelName(String levelName) {
		this.levelName = levelName;
	}

	public String getTitleName() {
		return titleName;
	}

	public void setTitleName(String titleName) {
		this.titleName = titleName;
	}

	public String getCourseContent() {
		return courseContent;
	}

	public void setCourseContent(String courseContent) {
		this.courseContent = courseContent;
	}

	public String getCouName() {
		return couName;
	}

	public void setCouName(String couName) {
		this.couName = couName;
	}
    
}