package com.msr.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class Student {
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_id
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    private Integer stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_name
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_sex
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    private String stuSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_birthday
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    @DateTimeFormat(pattern ="yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+9")
    private Date stuBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_tel
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    private String stuTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_address
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    private String stuAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_beginTime
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    @DateTimeFormat(pattern ="yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+9")
    private Date stuBegintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_endTime
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    @DateTimeFormat(pattern ="yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+9")
    private Date stuEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_status
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    private Integer stuStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.clazz_id
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    private Integer clazzId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.company_id
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.teacher_id
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_note
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    private String stuNote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_id
     *
     * @return the value of student.stu_id
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_id
     *
     * @param stuId the value for student.stu_id
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_name
     *
     * @return the value of student.stu_name
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_name
     *
     * @param stuName the value for student.stu_name
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_sex
     *
     * @return the value of student.stu_sex
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public String getStuSex() {
        return stuSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_sex
     *
     * @param stuSex the value for student.stu_sex
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public void setStuSex(String stuSex) {
        this.stuSex = stuSex == null ? null : stuSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_birthday
     *
     * @return the value of student.stu_birthday
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public Date getStuBirthday() {
        return stuBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_birthday
     *
     * @param stuBirthday the value for student.stu_birthday
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public void setStuBirthday(Date stuBirthday) {
        this.stuBirthday = stuBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_tel
     *
     * @return the value of student.stu_tel
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public String getStuTel() {
        return stuTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_tel
     *
     * @param stuTel the value for student.stu_tel
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public void setStuTel(String stuTel) {
        this.stuTel = stuTel == null ? null : stuTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_address
     *
     * @return the value of student.stu_address
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public String getStuAddress() {
        return stuAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_address
     *
     * @param stuAddress the value for student.stu_address
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public void setStuAddress(String stuAddress) {
        this.stuAddress = stuAddress == null ? null : stuAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_beginTime
     *
     * @return the value of student.stu_beginTime
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public Date getStuBegintime() {
        return stuBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_beginTime
     *
     * @param stuBegintime the value for student.stu_beginTime
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public void setStuBegintime(Date stuBegintime) {
        this.stuBegintime = stuBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_endTime
     *
     * @return the value of student.stu_endTime
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public Date getStuEndtime() {
        return stuEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_endTime
     *
     * @param stuEndtime the value for student.stu_endTime
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public void setStuEndtime(Date stuEndtime) {
        this.stuEndtime = stuEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_status
     *
     * @return the value of student.stu_status
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public Integer getStuStatus() {
        return stuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_status
     *
     * @param stuStatus the value for student.stu_status
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public void setStuStatus(Integer stuStatus) {
        this.stuStatus = stuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.clazz_id
     *
     * @return the value of student.clazz_id
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public Integer getClazzId() {
        return clazzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.clazz_id
     *
     * @param clazzId the value for student.clazz_id
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public void setClazzId(Integer clazzId) {
        this.clazzId = clazzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.company_id
     *
     * @return the value of student.company_id
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.company_id
     *
     * @param companyId the value for student.company_id
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.teacher_id
     *
     * @return the value of student.teacher_id
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.teacher_id
     *
     * @param teacherId the value for student.teacher_id
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_note
     *
     * @return the value of student.stu_note
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public String getStuNote() {
        return stuNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_note
     *
     * @param stuNote the value for student.stu_note
     *
     * @mbggenerated Wed Jul 10 13:49:28 JST 2019
     */
    public void setStuNote(String stuNote) {
        this.stuNote = stuNote == null ? null : stuNote.trim();
    }
}