package com.msr.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_id
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_name
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    private String teacherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_sex
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    private Integer teacherSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_birthday
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    @DateTimeFormat(pattern ="yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+9")
    private Date teacherBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_tel
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    private String teacherTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_address
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    private String teacherAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_status
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    private Integer teacherStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_note
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    private String teacherNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.hiredate
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    @DateTimeFormat(pattern ="yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+9")
    private Date hiredate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.leavedate
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    @DateTimeFormat(pattern ="yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+9")
    private Date leavedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.clazz_id
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    private Integer clazzId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_id
     *
     * @return the value of teacher.teacher_id
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_id
     *
     * @param teacherId the value for teacher.teacher_id
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_name
     *
     * @return the value of teacher.teacher_name
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_name
     *
     * @param teacherName the value for teacher.teacher_name
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName == null ? null : teacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_sex
     *
     * @return the value of teacher.teacher_sex
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    public Integer getTeacherSex() {
        return teacherSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_sex
     *
     * @param teacherSex the value for teacher.teacher_sex
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    public void setTeacherSex(Integer teacherSex) {
        this.teacherSex = teacherSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_birthday
     *
     * @return the value of teacher.teacher_birthday
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    public Date getTeacherBirthday() {
        return teacherBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_birthday
     *
     * @param teacherBirthday the value for teacher.teacher_birthday
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    public void setTeacherBirthday(Date teacherBirthday) {
        this.teacherBirthday = teacherBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_tel
     *
     * @return the value of teacher.teacher_tel
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    public String getTeacherTel() {
        return teacherTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_tel
     *
     * @param teacherTel the value for teacher.teacher_tel
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    public void setTeacherTel(String teacherTel) {
        this.teacherTel = teacherTel == null ? null : teacherTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_address
     *
     * @return the value of teacher.teacher_address
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    public String getTeacherAddress() {
        return teacherAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_address
     *
     * @param teacherAddress the value for teacher.teacher_address
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    public void setTeacherAddress(String teacherAddress) {
        this.teacherAddress = teacherAddress == null ? null : teacherAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_status
     *
     * @return the value of teacher.teacher_status
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    public Integer getTeacherStatus() {
        return teacherStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_status
     *
     * @param teacherStatus the value for teacher.teacher_status
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    public void setTeacherStatus(Integer teacherStatus) {
        this.teacherStatus = teacherStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_note
     *
     * @return the value of teacher.teacher_note
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    public String getTeacherNote() {
        return teacherNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_note
     *
     * @param teacherNote the value for teacher.teacher_note
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    public void setTeacherNote(String teacherNote) {
        this.teacherNote = teacherNote == null ? null : teacherNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.hiredate
     *
     * @return the value of teacher.hiredate
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    public Date getHiredate() {
        return hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.hiredate
     *
     * @param hiredate the value for teacher.hiredate
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    public void setHiredate(Date hiredate) {
        this.hiredate = hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.leavedate
     *
     * @return the value of teacher.leavedate
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    public Date getLeavedate() {
        return leavedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.leavedate
     *
     * @param leavedate the value for teacher.leavedate
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    public void setLeavedate(Date leavedate) {
        this.leavedate = leavedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.clazz_id
     *
     * @return the value of teacher.clazz_id
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    public Integer getClazzId() {
        return clazzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.clazz_id
     *
     * @param clazzId the value for teacher.clazz_id
     *
     * @mbggenerated Wed Jul 10 13:13:33 JST 2019
     */
    public void setClazzId(Integer clazzId) {
        this.clazzId = clazzId;
    }
}