package com.msr.entity;

public class CourseTitle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_title.title_id
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    private Integer titleId;//主题编号

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_title.title_name
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    private String titleName;//主题名称

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_title.title_level
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    private Integer titleLevel;//阶段编号（1、代表 一阶段	2、代表二阶段	3、代表三阶段	4、代表四阶段）

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_title.title_id
     *
     * @return the value of course_title.title_id
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    public Integer getTitleId() {
        return titleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_title.title_id
     *
     * @param titleId the value for course_title.title_id
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    public void setTitleId(Integer titleId) {
        this.titleId = titleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_title.title_name
     *
     * @return the value of course_title.title_name
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    public String getTitleName() {
        return titleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_title.title_name
     *
     * @param titleName the value for course_title.title_name
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    public void setTitleName(String titleName) {
        this.titleName = titleName == null ? null : titleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_title.title_level
     *
     * @return the value of course_title.title_level
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    public Integer getTitleLevel() {
        return titleLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_title.title_level
     *
     * @param titleLevel the value for course_title.title_level
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    public void setTitleLevel(Integer titleLevel) {
        this.titleLevel = titleLevel;
    }
}