package com.msr.mapper;

import com.msr.entity.CourseTitle;
import com.msr.entity.CourseTitleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseTitleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_title
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    int countByExample(CourseTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_title
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    int deleteByExample(CourseTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_title
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    int deleteByPrimaryKey(Integer titleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_title
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    int insert(CourseTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_title
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    int insertSelective(CourseTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_title
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    List<CourseTitle> selectByExample(CourseTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_title
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    CourseTitle selectByPrimaryKey(Integer titleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_title
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    int updateByExampleSelective(@Param("record") CourseTitle record, @Param("example") CourseTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_title
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    int updateByExample(@Param("record") CourseTitle record, @Param("example") CourseTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_title
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    int updateByPrimaryKeySelective(CourseTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_title
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    int updateByPrimaryKey(CourseTitle record);
}