package com.msr.entity;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_id
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    private Integer courseId;//课程编号

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_day
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    private String courseDay;//？

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_name
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    private String courseName;//课程名称

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_content
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    private String courseContent;//课程内容

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.title_id
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    private Integer titleId;//引入CourseTitle

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_id
     *
     * @return the value of course.course_id
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_id
     *
     * @param courseId the value for course.course_id
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_day
     *
     * @return the value of course.course_day
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    public String getCourseDay() {
        return courseDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_day
     *
     * @param courseDay the value for course.course_day
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    public void setCourseDay(String courseDay) {
        this.courseDay = courseDay == null ? null : courseDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_name
     *
     * @return the value of course.course_name
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_name
     *
     * @param courseName the value for course.course_name
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_content
     *
     * @return the value of course.course_content
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    public String getCourseContent() {
        return courseContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_content
     *
     * @param courseContent the value for course.course_content
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    public void setCourseContent(String courseContent) {
        this.courseContent = courseContent == null ? null : courseContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.title_id
     *
     * @return the value of course.title_id
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    public Integer getTitleId() {
        return titleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.title_id
     *
     * @param titleId the value for course.title_id
     *
     * @mbggenerated Fri Jul 12 16:21:09 JST 2019
     */
    public void setTitleId(Integer titleId) {
        this.titleId = titleId;
    }
}